# Generated by Django 5.1.6 on 2025-02-10 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('tipo', models.CharField(max_length=45, null=True)),
                ('url_video', models.URLField(null=True)),
            ],
            options={
                'db_table': 'Ejercicio',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('fecha', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Expediente',
            },
        ),
        migrations.CreateModel(
            name='Fisioterapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100, null=True)),
                ('codigo_token', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Fisioterapeuta',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.ejercicio')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.fisioterapeuta')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('nacionalidad', models.CharField(max_length=45, null=True)),
                ('telefono', models.CharField(max_length=45, null=True)),
                ('foto_url', models.CharField(max_length=45, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=45, null=True)),
                ('persona_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.persona')),
            ],
            options={
                'db_table': 'Paciente',
            },
        ),
        migrations.AddField(
            model_name='fisioterapeuta',
            name='persona_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.persona'),
        ),
        migrations.CreateModel(
            name='SeguimientoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_ia', models.TextField(null=True)),
                ('url_video_paciente', models.URLField(null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.paciente')),
            ],
            options={
                'db_table': 'Seguimiento_IA',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFisioterapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.estado')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.feedback')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.paciente')),
            ],
            options={
                'db_table': 'Feedback_Fisioterapeuta',
                'unique_together': {('paciente', 'feedback')},
            },
        ),
        migrations.CreateModel(
            name='ExpedienteHasPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion', models.DateField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.expediente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.paciente')),
            ],
            options={
                'db_table': 'Expediente_Has_Paciente',
                'unique_together': {('expediente', 'paciente')},
            },
        ),
        migrations.CreateModel(
            name='EjercicioAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignada', models.DateTimeField(null=True)),
                ('fecha_limite', models.DateTimeField(null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.ejercicio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.estado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.paciente')),
            ],
            options={
                'db_table': 'Ejercicio_Asignado',
                'unique_together': {('paciente', 'ejercicio')},
            },
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20, null=True)),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.fisioterapeuta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.paciente')),
            ],
            options={
                'db_table': 'Vinculacion',
                'unique_together': {('fisioterapeuta', 'paciente')},
            },
        ),
    ]
