# Generated by Django 5.1.6 on 2025-02-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
