# Generated by Django 5.1.6 on 2025-02-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_persona_foto_url_alter_persona_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
