# Generated by Django 5.1.6 on 2025-03-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_ejercicio_descripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ejercicioasignado',
            unique_together=set(),
        ),
    ]
