# Generated by Django 5.1.6 on 2025-03-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_alter_ejercicioasignado_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoia',
            name='ejercicio_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.ejercicioasignado'),
        ),
    ]
