# Generated by Django 5.1.6 on 2025-03-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_seguimientoia_ejercicio_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientoia',
            name='paciente',
        ),
    ]
