# Generated by Django 5.1.7 on 2025-03-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_remove_seguimientoia_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='seguimientoia',
            name='url_video_paciente',
        ),
        migrations.AddField(
            model_name='ejercicioasignado',
            name='url_video_paciente',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ejercicio_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.ejercicioasignado'),
        ),
        migrations.DeleteModel(
            name='FeedbackFisioterapeuta',
        ),
    ]
