# Generated by Django 5.1.7 on 2025-04-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_remove_feedback_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicioasignado',
            name='url_video_paciente',
            field=models.FileField(blank=True, null=True, upload_to='storage/'),
        ),
    ]
