# Generated by Django 5.1.7 on 2025-04-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_alter_ejercicioasignado_url_video_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nacionalidad',
        ),
    ]
