# Generated by Django 5.1.7 on 2025-05-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_remove_persona_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicioasignado',
            name='url_video_paciente',
            field=models.FileField(blank=True, null=True, upload_to='storage/exercise/assigment/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto_url',
            field=models.FileField(blank=True, null=True, upload_to='storage/profile/photo/'),
        ),
    ]
