# Generated by Django 5.1.7 on 2025-05-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_alter_ejercicioasignado_url_video_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_audio',
            field=models.FileField(blank=True, null=True, upload_to='storage/feedback/audio'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_imagen',
            field=models.FileField(blank=True, null=True, upload_to='storage/feedback/imagen'),
        ),
    ]
